"""create_download_jobs_table

Revision ID: 6dcd9f500d3f
Revises: 97a39bb1c7e5
Create Date: 2026-07-11 22:05:00.328762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dcd9f500d3f'
down_revision: Union[str, Sequence[str], None] = '97a39bb1c7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.Column('saved_words', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('categories', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('difficulty_levels', 'level',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('difficulty_levels', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('difficulty_levels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('languages', 'flag',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('languages', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('languages', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('languages', 'downloadable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('languages', 'downloaded',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('languages', 'download_size',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('languages', 'version',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('languages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'learning_language_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'learning_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'difficulty_level_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'words_per_session',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('20'))
    op.drop_column('users', 'learning_language')
    op.drop_column('users', 'learning_category')
    op.drop_column('users', 'learning_level')
    op.alter_column('vocabulary', 'pronunciation',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('vocabulary', 'part_of_speech',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('vocabulary', 'cefr_level',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('vocabulary', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('vocabulary', 'example_sentence',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('vocabulary', 'example_translation',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('vocabulary', 'audio_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('vocabulary', 'image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('vocabulary', 'source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               nullable=False,
               existing_server_default=sa.text("'ollama'::character varying"))
    op.alter_column('vocabulary', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vocabulary', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vocabulary', 'source',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'ollama'::character varying"))
    op.alter_column('vocabulary', 'image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('vocabulary', 'audio_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('vocabulary', 'example_translation',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('vocabulary', 'example_sentence',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('vocabulary', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('vocabulary', 'cefr_level',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('vocabulary', 'part_of_speech',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('vocabulary', 'pronunciation',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.add_column('users', sa.Column('learning_level', sa.VARCHAR(length=10), server_default=sa.text("'A1'::character varying"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('learning_category', sa.VARCHAR(length=100), server_default=sa.text("'Daily Conversation'::character varying"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('learning_language', sa.VARCHAR(length=50), server_default=sa.text("'German'::character varying"), autoincrement=False, nullable=True))
    op.alter_column('users', 'words_per_session',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('20'))
    op.alter_column('users', 'difficulty_level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'learning_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'learning_language_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('languages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('languages', 'version',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('languages', 'download_size',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('languages', 'downloaded',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('languages', 'downloadable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('languages', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('languages', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('languages', 'flag',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('difficulty_levels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('difficulty_levels', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('difficulty_levels', 'level',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_table('download_jobs')
    # ### end Alembic commands ###
